In [ ]:

import numpy as np

def convolution_with_zero_padding(matrix, kernel):


    if not isinstance(matrix, np.ndarray) or not isinstance(kernel, np.ndarray):
        raise ValueError("Đầu vào phải là numpy array")
    

    matrix_height, matrix_width = matrix.shape
    kernel_height, kernel_width = kernel.shape

    pad_height = kernel_height // 2
    pad_width = kernel_width // 2
    
    padded_matrix = np.pad(
        matrix,
        pad_width=((pad_height, pad_height), (pad_width, pad_width)),
        mode='constant',
        constant_values=0
    )
    
    output = np.zeros((matrix_height, matrix_width))
    
    for i in range(matrix_height):
        for j in range(matrix_width):
            matrix_patch = padded_matrix[i:i+kernel_height, j:j+kernel_width]
            
            output[i, j] = np.sum(matrix_patch * kernel)
    
    return output

matrix = np.array([
    [5, 2, 4, 6, 0],
    [1, 6, 1, 0, 6],
    [7, 7, 1, 6, 7],
    [7, 1, 4, 6, 0],
    [0, 2, 7, 0, 1]
])

kernel = np.array([
    [2, -1, 1],
    [-1, 0, 1],
    [1, 2, 1],
])

result = convolution_with_zero_padding(matrix, kernel)

print("Ma trận gốc:")
print(matrix)
print("\nKernel:")
print(kernel)
print("\nKết quả tích chập (giữ nguyên kích thước):")
print(result)


Ma trận gốc:
[[5 2 4 6 0]
 [1 6 1 0 6]
 [7 7 1 6 7]
 [7 1 4 6 0]
 [0 2 7 0 1]]

Kernel:
[[ 2 -1  1]
 [-1  0  1]
 [ 1  2  1]]

Kết quả tích chập (giữ nguyên kích thước):
[[10. 13. 12.  3.  6.]
 [24. 34. 15. 27. 32.]
 [27.  4. 25. 30. -6.]
 [ 3. 16. 40.  7.  1.]
 [-4. 24.  2. -4. 12.]]
