## model thử nghiệm tối ưu tốc độ

In [57]:
# 1. Load và xử lý dữ liệu
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd


In [55]:

# Load dataset
iris = load_iris()
X = iris.data
y = iris.target

y


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [58]:
df = pd.DataFrame(X, columns=iris.feature_names)
df['target'] = y  # Thêm cột target vào cuối

# Xem 5 dòng đầu
print(df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  


In [35]:
# l = np.eye(3)[y]
# l[-5:]

In [36]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [37]:
print(dir(iris))  # Liệt kê mọi thuộc tính/phương thức

['DESCR', 'data', 'data_module', 'feature_names', 'filename', 'frame', 'target', 'target_names']


In [38]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:

# Chuẩn hóa dữ liệu
X = (X - np.mean(X, axis=0)) / np.std(X, axis=0)
X   

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [40]:

# One-hot encoding cho target
def one_hot(y, classes):
    return np.eye(classes)[y]
y_onehot = one_hot(y, 3)

y_onehot


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [41]:

# Chia tập train/test
np.random.seed(42)
indices = np.random.permutation(len(X))
train_size = int(0.8 * len(X))
X_train, y_train = X[indices[:train_size]], y_onehot[indices[:train_size]]
X_test, y_test = X[indices[train_size:]], y_onehot[indices[train_size:]]


### thử nghiệm

In [76]:
in_t = np.random.randint(0,5,[7,4])
in_t

array([[0, 1, 1, 3],
       [0, 4, 4, 1],
       [0, 1, 2, 1],
       [1, 4, 4, 4],
       [2, 4, 0, 3],
       [0, 0, 4, 3],
       [3, 3, 2, 4]])

In [74]:
w_t = np.random.randint(0,5,[4,5])
w_t

array([[3, 0, 3, 2, 4],
       [3, 4, 0, 4, 4],
       [1, 1, 1, 4, 2],
       [4, 2, 2, 1, 3]])

In [77]:
t_dot = np.dot(in_t,w_t)
t_dot

array([[16, 11,  7, 11, 15],
       [20, 22,  6, 33, 27],
       [ 9,  8,  4, 13, 11],
       [35, 28, 15, 38, 40],
       [30, 22, 12, 23, 33],
       [16, 10, 10, 19, 17],
       [36, 22, 19, 30, 40]])

In [78]:
t1 = np.random.randint(0,5,[7,4])
t1
t2 = np.random.randint(0,5,[5,4])
t2 
t_dot2 = np.dot(t1,t2)
t_dot2


ValueError: shapes (7,4) and (5,4) not aligned: 4 (dim 1) != 5 (dim 0)

In [42]:
l = np.random.permutation(len(X))  # VD: [2,0,3,1,4,...]
l

array([ 84,  20,  45,  47, 149, 114, 144, 117,   9,  90, 146,  14,  33,
       141,  13,  77,  46,   5,   3,   7, 123,  49, 148, 101,  75,  48,
        21, 108,  60,  62,  42,  56, 125, 116,  59,   4,  99, 112,  89,
        63, 145,  66,  34,  41, 139,  30,  22,  24, 137, 118,  88,  79,
        17,  98,  39,  32,  40, 100,   6,  81,  94,  64,  73,  25, 122,
       147,  72,  19, 113,  93,  15,  10,  82,  68, 109,  37,  16, 111,
       132,  54,  67, 134, 119, 106, 110,  52, 130,  18,   0,  86,  53,
        92,  97, 136,  80,  55, 121,   1,  38,  11, 103,  57, 124,  51,
        87,  95,  31,  58,  78,  23, 135, 105,  50,  96,  36, 126,   8,
       131,  71,  69, 102,   2, 104,  76, 115, 129, 140,  26, 120, 128,
        91, 127,  74,  29,  83,  43, 107, 138, 143, 133,  61,  44,  65,
        27,  85,  70,  12,  35,  28, 142])

In [60]:
W1 = np.random.randn(4, 5) * 0.01
W1 

array([[-0.01500768,  0.00165023, -0.00855929, -0.00039636, -0.00534663],
       [-0.01788497,  0.00357305, -0.00414532,  0.00080199, -0.0089312 ],
       [-0.00334817,  0.0156038 ,  0.00128551,  0.00549576, -0.01270872],
       [ 0.02389036,  0.01843414,  0.01363435,  0.00828766,  0.00015143]])

In [61]:
b1 = np.zeros((1, 5))
b1

array([[0., 0., 0., 0., 0.]])

In [62]:
W2 = np.random.randn(5, 3) * 0.01
W2

array([[ 0.00442074,  0.0104802 , -0.0062857 ],
       [-0.00444499, -0.01669132, -0.00771819],
       [ 0.01661302, -0.00334247, -0.00317847],
       [ 0.00317767, -0.01612227,  0.00945382],
       [ 0.01266407,  0.00377296,  0.01651351]])

In [64]:
b2 = np.zeros((1, 3))
b2


array([[0., 0., 0.]])

In [65]:
z1 = np.dot(X, W1) + b1
z1


array([[-0.13904594,  0.04645397, -0.0536344 ,  0.01013711, -0.07628893],
       [-0.12710192,  0.0443374 , -0.04984989,  0.00981539, -0.070754  ],
       [-0.12734255,  0.04316159, -0.04909564,  0.00950548, -0.07020004],
       [-0.12472292,  0.04576002, -0.04756808,  0.01056407, -0.07131401],
       [-0.13933366,  0.04664625, -0.05319301,  0.01025695, -0.07664739],
       [-0.14692861,  0.05674623, -0.05474779,  0.01364526, -0.08524773],
       [-0.12736456,  0.04711497, -0.04757679,  0.01108386, -0.07270735],
       [-0.13609149,  0.04749202, -0.05223539,  0.01064613, -0.07613202],
       [-0.11780958,  0.04315498, -0.04515571,  0.00993337, -0.06718757],
       [-0.13161427,  0.04441167, -0.0514993 ,  0.0096164 , -0.07293314],
       [-0.14746005,  0.04922403, -0.0569027 ,  0.01072818, -0.08095003],
       [-0.13342477,  0.04872236, -0.05039498,  0.01127497, -0.07633356],
       [-0.12799018,  0.04232897, -0.05035739,  0.00902626, -0.07023448],
       [-0.11948189,  0.03682271, -0.0

In [ ]:
a1 = sigmoid(z1)
a1  


In [ ]:
z2 = np.dot(a1, W2) + b2
z2


In [ ]:
a2 = sigmoid(z2)
a2

In [43]:

# 2. Triển khai ANN từ đầu
class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        # Khởi tạo weights
        self.W1 = np.random.randn(input_size, hidden_size) * 0.01
        self.b1 = np.zeros((1, hidden_size))
        self.W2 = np.random.randn(hidden_size, output_size) * 0.01
        self.b2 = np.zeros((1, output_size))
    
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def sigmoid_deriv(self, x):
        return x * (1 - x)
    
    def forward(self, X):
        self.z1 = np.dot(X, self.W1) + self.b1
        self.a1 = self.sigmoid(self.z1)
        self.z2 = np.dot(self.a1, self.W2) + self.b2
        self.a2 = self.sigmoid(self.z2)
        return self.a2
    
    def backward(self, X, y, output, lr=0.01):
        # Tính gradient
        error = output - y
        delta2 = error * self.sigmoid_deriv(output)
        dW2 = np.dot(self.a1.T, delta2)
        db2 = np.sum(delta2, axis=0, keepdims=True)
        
        delta1 = np.dot(delta2, self.W2.T) * self.sigmoid_deriv(self.a1)
        dW1 = np.dot(X.T, delta1)
        db1 = np.sum(delta1, axis=0)
        
        # Cập nhật weights
        self.W2 -= lr * dW2
        self.b2 -= lr * db2
        self.W1 -= lr * dW1
        self.b1 -= lr * db1
    
    def train(self, X, y, epochs=1000, lr=0.01):
        for epoch in range(epochs):
            output = self.forward(X)
            self.backward(X, y, output, lr)
            
            if epoch % 100 == 0:
                loss = np.mean(np.square(output - y))
                print(f"Epoch {epoch}, Loss: {loss:.4f}")


In [44]:
np.random.randn(4, 5) * 0.01


array([[-0.00751179, -0.01130428,  0.00769977,  0.0126839 ,  0.00424486],
       [ 0.00940536, -0.00867641,  0.00145862, -0.01369871, -0.00771781],
       [ 0.00878674, -0.00239595,  0.01209382,  0.0053796 ,  0.02734422],
       [ 0.00093765, -0.01406405, -0.0003453 , -0.00963016,  0.0097718 ]])

In [45]:
np.zeros((1, 5))

array([[0., 0., 0., 0., 0.]])

In [46]:

# 3. Tạo và huấn luyện mô hình
nn = NeuralNetwork(input_size=4, hidden_size=5, output_size=3)
nn.train(X_train, y_train, epochs=1000, lr=0.1)


Epoch 0, Loss: 0.2508
Epoch 100, Loss: 0.0202
Epoch 200, Loss: 0.0133
Epoch 300, Loss: 0.0119
Epoch 400, Loss: 0.0113
Epoch 500, Loss: 0.0109
Epoch 600, Loss: 0.0107
Epoch 700, Loss: 0.0105
Epoch 800, Loss: 0.0104
Epoch 900, Loss: 0.0103


In [47]:

# 4. Đánh giá mô hình
def accuracy(y_true, y_pred):
    return np.mean(np.argmax(y_true, axis=1) == np.argmax(y_pred, axis=1))

test_pred = nn.forward(X_test)
print(f"\nTest Accuracy: {accuracy(y_test, test_pred):.2%}")



Test Accuracy: 100.00%


In [59]:

# 5. Dự đoán mẫu mới
sample = np.array([[5.1, 3.5, 1.4, 0.2]])  # Chuẩn hóa theo cùng tham số
sample = (sample - np.mean(X, axis=0)) / np.std(X, axis=0)
prediction = nn.forward(sample)
print(f"Predicted class: {iris.target_names[np.argmax(prediction)]}")

Predicted class: setosa
